### ISSUE TITLE
failed transactions are being counted together with completed transactions and subscriptions are being prematurely marked completed

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#102]
Part of: https://github.com/iATSPayments/com.iatspayments.civicrm/issues/93 - reported by Tamar

**Comment by KarinG** [comment]
Going to try and reproduce this now on a 4.6.10

**Comment by KarinG** [comment]
I've reproduced it for this scenario: credit card expires before number of installments (with contribution status = completed) - equals the total number of installments in the recurring series. Looking into this now.

**Comment by KarinG** [comment]
Found this issue; will check in w/ Alan on this tomorrow.

**Comment by KarinG** [comment]
I think this fixes it - if not please do let us know.

**Comment by tamarmeir** [comment]
Hi Karin,

It has only been a short while since we implemented the fix in our client environments and I wonder if you could clarify point number 2 for me since this is what looks to be the case: 

1. If an installment fails, the extension will attempt to charge on a daily basis until a successful installment is processed or the subscription is cancelled
2. Even though the extension continues to attempt charging the installment, as soon as the number of completed + failed contributions = number of installments, the extension will mark the subscription as completed and update the end date of the subscription according to the last failed attempt?

Thanks in advance for your time,
Tamar

**Comment by KarinG** [comment]
Hi Tamar,
I thought I had fixed that in the commit reference above:  
+        AND (c.contribution_status_id IN (1,2)) 
this means that we only count them if contribution status is Completed or Pending (need that for ACH/EFT); by adding this in Failed contributions e.g. are no longer counted - if however this is not working - let me know - and I'll gladly have another pass at this. -- KarinG

**Comment by tamarmeir** [comment]
Hi Karin,

Many thanks for your quick response. I've confirmed it:

* Failed contributions continue to be created for a subscription with an expired credit card
* The subscription status is "Completed" and the end date of the subscription matches that of the last failed installment (it was 2016-01-11 when I checked before confirming my hunch)
* To confirm my hunch, I manually executed the iATS Payments Recurring Contributions scheduled job - a new failed contribution was created and the the end date of the subscription was updated to 2016-01-12
* I'm thinking the fix that you made is checking the number of **completed** contributions against the total number of expected installments to determine whether to generate another contribution, but perhaps the part of the code that updates the subscription status also needs to be updated?

Thanks again for looking into this,
Tamar

**Comment by KarinG** [comment]
Hi Tamar - I'll make time to look into this tomorrow. -- KarinG

**Comment by KarinG** [comment]
Hi - there are lots of bits here - keep in mind there may be some confusion - as many of your recurring series would have been started before you added this code fix. 

1. we're now properly checking installments_done vs installments (do be done) - even for recurring series marked Completed or in Progress - as the number of installments may have changed (up or down).

2. so your first point - Failed contributions are created even though credit card is expired - that suggests that the number of installments to be done does not yet match the number of installments (completed or pending). So that's a good thing - it's trying again - and the Failed contribution is a note to your staff - to phone the member and update the credit card. 

3. Completed - ah that is legacy here - it used to be Completed - but it really wasn't. It does not affect the math/or the attempts - the code already evaluates whether a series is really Completed (or not). However - I have just added in some code to help with this transition. If we now discover that the number of installments done is still less than the number of installments to be done -> I'm now explicitly setting the contribution_status_id for the series to 5 (in progress):

https://github.com/iATSPayments/com.iatspayments.civicrm/commit/12087f107cce265c95febb5df7ef8a81885193a5

**Comment by KarinG** [comment]
I think this fixes it - if not please do let us know.

**Comment by tamarmeir** [comment]
Hi Karin,

Perfect! While I know it doesn't affect the math within the extension, the status of the recurring subscription is important both for built in reports (where a user may opt to exclude completed subscriptions since (one would expect), nothing further is due on them), and it affects the math that will exclude recurring subscriptions in a status of "Complete" from appearing as an open balance for some custom code that we have (and possibly other built in civi reports that may be based on recurring subscription status).

Thanks so much for your speedy response! It is greatly appreciated. Once we get our client environments updated I will be back in touch to let you know if all is well.

Kind regards,
Tamar

**Comment by adixon** [comment]
Yes, and for what it's worth - the next version of the extension will come with some additional tools for managing cc failures - e.g. it's now going to be populating the 'failure_count' field.

**Comment by tamarmeir** [comment]
Oh, that's worth a LOT! But I will keep myself from going off on a tangent until we get the updated version installed.

Thanks Alan!

**Comment by KarinG** [comment]
We really appreciate you reporting these issues in detail Tamar. Don't hesitate to let us know if you encounter any more bananas.

**Comment by mlutfy** [comment]
Just double-checking: would the SQL fix also need to be applied in the query around this line:
https://github.com/iATSPayments/com.iatspayments.civicrm/blob/12087f107cce265c95febb5df7ef8a81885193a5/api/v3/Job/Iatsrecurringcontributions.php#L344

so that a transaction is not prematurely marked as "completed" if a transaction failed?

**Comment by adixon** [comment]
Yes, you're right, done, thanks.

It would actually get processed - that sql is only for optics between runs (because the sql gets rerun).

**Comment by tamarmeir** [comment]
Hi guys,

Just wanted to report back that I have double checked the status issue that was fixed during the code sprint and deployed to our clients late last week and all is AOK! Thanks so much for your efforts, and I LOVE the added flexibility you have included to manage credit card details.... but more on this in a different "issue".

Kind regards,
Tamar

**Comment by KarinG** [comment]
Excellent - great to hear! Keep poking us if you find any more issues - and/or if there are any other things that are important to you. I know you're working off master - we'll have a proper release for that soon.
