### ISSUE TITLE
Recurring ACH/EFT contribution

### ISSUE THREAD

**Issue by waddyvic** [iATSPayments/com.iatspayments.civicrm#115]
I'm using CiviCRM 4.6.10 and iATS payments v1.4.2. I can setup recurring credit card contribution within CiviCRM, but I don't see an option to setup recurring ACH/EFT contribution. I've created an iATS ACH/EFT payment processor. Am I missing something?

**Comment by KarinG** [comment]
Once you have created the ACH/EFT payment processor you can eg add it to a contribution page.

**Comment by adixon** [comment]
Did this work? It wasn't clear from your question whether your challenge was getting the ACH/EFT payment processor as an option, or the recurring option was missing?

One bit that isn't super obvious is that the name you give to the payment processor will show up both as the option you choose on the contribution admin page and also for the public. So you'll want to call it 'Direct Deposit' instead of the more technical ACH/EFT, since that's what most people think of it as.

**Comment by waddyvic** [comment]
No, I'm not trying to setup a contribution page. I was trying to find out if CiviCRM can setup recurring ACH/EFT contribution manually from the Admin UI. I could setup a recurring credit card contribution with iATS credit card payment processor, but not ACH/EFT even after I've created an iATS ACH/EFT payment processor.

**Comment by adixon** [comment]
Ah, a good question. The ACH/EFT payment processors were pulled from the admin contribution pages because they used to break them. It might now work in 4.6 and you could try removing that code (about line 868 on iats.php file). What I've always done instead is use this extension
https://github.com/adixon/ca.civicrm.contributextra
to set a dedicated contribution page for administrative use. That method has the advantage of simplifying an adminstrator's task in setting up new ACH/EFT payments.

**Comment by waddyvic** [comment]
Well it's been more than a year, and I finally have time to dive into this. I used your ca.civicrm.contributextra extension on a sandbox installation and it works well. Thx for the help!
