### ISSUE TITLE
Two separate entries for recurring contributions in same month.

### ISSUE THREAD

**Issue by Edzelopez** [iATSPayments/com.iatspayments.civicrm#130]
Hi,

One of our clients have an issue wherein a contact has been charged twice in the same month for a recurring contribution. The contribution is set to charge $50 per month on the 21st. The initial payment was made on 21st Jan, 2016 and subsequent payments were made on 21st Feb 2016 and 21st March 2016.
Here are entries from iATS.

![iats](https://cloud.githubusercontent.com/assets/1990869/14042670/2d49aeae-f2a2-11e5-95e9-b70ed76efa12.png)

As you can see, the charges on the 21st of Feb & March do not have invoice IDs. Also, there has been another incorrect charge on the 23rd of March which does have the invoice ID. Only the charge from the 23rd of March has been successfully recorded as a recurring activity in CiviCRM, although it is the wrong one. Please let me know if you need more information or if you need me to troubleshoot further.

**Comment by adixon** [comment]
The absence of an invoice id and the fact it doesn't show up in CiviCRM suggests that the Feb/Mar 21 transactions were not initiated from CiviCRM. Perhaps this recurring contribution was setup as an iATS-managed recurring contribution instead of a CiviCRM recurring contribution? Or perhaps initially setup as a CiviCRM contribution, and then the first one didn't work because the cron wasn't setup so someone went into iATS and turned on recurrance there, and then the cron did get setup and triggered the Mar 23 one? I'm guessing there's a fair bit of missing background here. Try looking in iATS at the client record, you should see there that recurring is off.

**Comment by JoeMurray** [comment]
Thanks for the useful assistance.

**Comment by Edzelopez** [comment]
Hi @adixon 

Here is another instance of a person who has been charged twice in the same month. In this case, there were invoice IDs for both.
![iats heidi](https://cloud.githubusercontent.com/assets/1990869/15071009/1c5ec7ee-13a6-11e6-9319-63b64c9fe911.png)

I should also mention that when I checked the client record in iATS, the recurring was set to ON. Is that supposed to be activated or is that the reason iATS is charging the client double?

**Comment by KarinG** [comment]
Hi Edzelopez, you definitivey want OFF for the config on iatspayments.com because then you will be charging the cards twice - one via the civicrm / cron / jobs and once via the one on iatspayments.com;

To have two transactions a few days apart and with a CiviCRM invoice ID: do you perhaps have a clone of your instance that is also generating recurring contributions. That's a CiviCRM id - a CiviCRM instance must have initiated that transaction.
