### ISSUE TITLE
Do we need to set a postback URL with IATS?

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#133]
This is a support question rather than a bug... or maybe it's a documentation suggestion?

Since most payment processors used in CiviCRM require setting a postback URL, I spent some time scratching my head on this one.

I think it is not necessary because of the daily scheduled job, but it might be useful to add that to the README.md file in the install section. 

Thanks for the great extension! At PTP we've started making IATS our recommended payment processor.

**Comment by adixon** [comment]
Thanks for the encouragement, and that's actually a timely question.

The short answer is definitely that we don't require a postback URL, and in fact iATS doesn't provide that functionality (i.e. any kind of IPN).

On the other hand, we're working on introducing the ability to have the processor manage the recurring schedules as an option. When we do, CiviCRM will be grabbing the data from iATS, rather than having it pushed to it via a postback.

The change from the earlier recurring contribution models definitely requires some thinking, and you'll see a longer screed here: https://civicrm.org/blog/alan-dixon/recurring-payments-advanced-functions

**Comment by jmcclelland** [comment]
Thanks for the timely answer.
