### ISSUE TITLE
Does this Extension use DPM (Direct Post Method)?

### ISSUE THREAD

**Issue by shaigluskin** [iATSPayments/com.iatspayments.civicrm#140]
Hi Folks,

Does iatspayments.civicrm use DPM to process transactions?

If the answer is yes, great!

If the answer is "No", then it seems to me, based on my recent study of PCI compliance, that sites using CiviCRM/iatspayments would be required to fill out "Self Assessment Questionnaire D" (SAQ D) which has 326-347 different controls to meet. If "No" do you have a different interpretation of PCI-DSS 3.0 from what I've just stated?

Thanks,

Shai Gluskin

**Comment by adixon** [comment]
Yes, that's a good question. I recently had the misfortune to setup a client with CiviCRM using Bluepay (they have an authnet compatible option) and they required us to go through a PCI compliance SAQ and scan with a company called 'Controlscan'. I asked them the same question, and they only requested SAQ-C, even though it's not using DPM. My take on it is that technically you need SAQ D, (i.e. as of the changes of Jan 2016), but no one really wants to insist, because it's fairly ludicrous (well, PCI compliance is a bit ludicrous to start with, but that's a separate conversation). It was an informative ordeal ...

The more nuanced answer is that we've been working on a DPM option for a while, but have concerns about it (mostly, about how to handle unexpected failures). It is still on our priority list and realistically it should be ready before the end of this year. In the meantime, I would not expect you to have to do SAQ D, but it might just depend on who you ask, and how.
