### ISSUE TITLE
params different in 4.7

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#145]
Notice: Undefined index: payment_processor_id in iats_civicrm_pre() (line 518 of /Applications/MAMP/htdocs/buildkit/build/dmaster/sites/default/files/civicrm/ext/com.iatspayments.civicrm/iats.php).

**Comment by KarinG** [comment]
Actually scratch that - it's not renamed - it's simply missing from the $params that get fed into here:

 if (('ContributionRecur' == $objectName) && ('create' == $op || 'edit' == $op))  {
    if ($type = _iats_civicrm_is_iats($params['payment_processor_id'])) {

**Comment by adixon** [comment]
So that means when new recurring contribution series are created, there's no payment processor id parameter? Or only under some circumstances? That code is intercepting the dates for cases of fixed days/month.

**Comment by KarinG** [comment]
Sending you a screenshot - this is straight-up recurring - credit card transaction - contribution in 4.7

**Comment by KarinG** [comment]
![params](https://cloud.githubusercontent.com/assets/5340555/16433399/50dd1442-3d47-11e6-8ca7-b6dc180a7e30.png)

**Comment by adixon** [comment]
Does this happen when you're trying to edit the recurring schedule via the standard civi interface?

If so, then it kind of makes sense - in that case, we're not doing anything related to the payment processor so we might think that we don't really need to include it in the params. On the other hand - this code is kicking in because we're need to test/check the next sched date. Wanna check the stack trace to see where this might be coming from?

**Comment by KarinG** [comment]
No - this is me running the Iatsrecurringcontributions scheduled job. Apparently pre is invoked there (now).

**Comment by adixon** [comment]
Fixed as part of 3d7db087a45024d613e2475b94e6467aa7ab873a on line 526.

It was actually the extension itself using the api to modify the recurring contribution record and not supplying the payment processor id.

It's an ugly piece of code, and it'll have to trust that any processes modifying the next recurring date are going to respect the allowable days if they don't supply the payment processor id.
