### ISSUE TITLE
ACH pending in Civi since TLS 1.2 site URL change

### ISSUE THREAD

**Issue by kngs** [iATSPayments/com.iatspayments.civicrm#190]
We recently changed our iATS payment processor configuration site url to https://www2.iatspayments.com/NetGate/ProcessLinkv2.asmx?WSDL as we go through the PCI compliance process.  Since then, ACH payments have been showing up OK in Civi's iATS Admin console but the contribution remains in the Pending (Incomplete Transaction) status. They show in ACHEFT Approval in our iATS Online Portal. And the funds are being pulled from the donors bank account.   The cron iATS Verification cron job never completes (also receiving "Invalid domain for date format"  from cron job).  We are TLS 1.2 compatible because many of our PCI compliance failures went away after the site URL change.  Is there another configuration change we need to make in order for this handshake to complete? The Credit Card transactions seem to be processing without issue since the URL change.

Note: We have intermittently received 9002 errors when making ACH payments prior to this change so it may not have been properly configured to begin with. We have had one 9002 Error since changing the site URL

**Comment by adixon** [comment]
1. The use of www2 is only needed if you don't have TLS 1.2. Using it won't affect your compliance. i.e. you only need it if you don't have TLS 1.2 (which is probably required for compliance by now). 

2. The lack of approval (i.e. ACH left in pending) is exactly because the verification job is not completing. That is likely to be related to the change in domain, i.e. the www2 server is not handling the verification job request properly, and sending you data with a different date format.

What you really need to do is to get TLS 1.2 and switch back to the www server. The www2 server is going to go away. Your lack of TLS 1.2 is probably a symptom of a system that is not up to date or maintained, that's the key issue.

**Comment by kngs** [comment]
Thanks, Alan, for straightening TLS 1.2 out for me.
Which URL should I point to?
https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL
https://www.iatspayments.com/NetGate/ProcessLinkv2.asmx?WSDL 

P.S. I  verified with my host I am TLS 1.2 compatible and have SOAP enabled, so still don't know what's causing the intermittent 9002 error (happens with both URLs).

**Comment by adixon** [comment]
Either one works, only the domain is actually used.
