### ISSUE TITLE
Setting up iATS but getting 9002 Error

### ISSUE THREAD

**Issue by henrywatts** [iATSPayments/com.iatspayments.civicrm#194]
Trying to set up iATS payment with CiviCRM.

Running CiviCRM version 4.7.17
iATS extension version 1.5.4-beta

We have created the payment processor accounts and put our credentials in, but get the following error:
Payment Processor Error 9002: Unexpected Server Error, please see your logs

We have checked our credentials, which we believe are correct and have simplified our password.  We have checked that it is not a firewall issue.  We have checked our SSL and TLS issues (running TLS 1.2).

None of our transactions are able to make it to iATS system (so they don't show up on merchant page after logging into iATS).

Any advice?

**Comment by KarinG** [comment]
Hi Henry - three thoughts:
- best to use our latest 4.7 Release Candidate: https://github.com/iATSPayments/com.iatspayments.civicrm/releases/tag/1.5.4-rc-2
- to check your credentials for the payment processor you've set up [that's typically an agent code ending in 80 or 81, etc] -> go and login with that Agent code and your password -> on iATSpayments.com - make sure you can log in
- ensure that the password does not have non-alphanumeric characters in it
- check with iATS that this agent code is configured such that you can transact with this via online webservices
- SSL and TLS -> confirm that you can do this from a command line:
`openssl s_client -quiet -tls1_2 -connect iatspayments.com:443`
[and not get handshake failures]

Let me know if that helps,

**Comment by henrywatts** [comment]
Hi Karin - thanks for the thoughts, I forwarded the first one to our developer for his response.  We are using the 80 code, and we can log in to iATSpayments.com using that code and the password.  We did update the password so that it only has letters and numbers.

The question I have for you is on the SSL and TLS - we are struggling to get this to work.  But, we have been testing for quite some time using the iATS test account TE0088 agent code and password.  That one works fine and is working now (I just did another test on it).  Would that be working if we didn't have the SSL/TLS set up correctly?

Thanks! Henry

**Comment by KarinG** [comment]
TE0088? Do you mean TEST88? Ask your developer to get into a shell and try a handshake with iATS (as I described above). Print the output here! Happy to help you figure this one out.

**Comment by henrywatts** [comment]
Thanks, Karin - both TE0088 and TEST88 are test accounts.  We had been using the TE0088 account.  Here is what Brian gave me from running the SSL/TLS test:
> when I do the recommended test I get: 
> root@db:~# openssl s_client -quiet -tls1_2 -connect iatspayments.com:443
> depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign CloudSSL CA - SHA256 - G3
> verify error:num=20:unable to get local issuer certificate
> verify return:0
> 
> If I pass the location of the certs, the handshake is successful:
> openssl s_client -CApath /etc/ssl/certs/ -connect iatspayments.com:443

We are trying to work through that with our server guy and the consultant server people.  But, I was curious as to why our test account transactions were working - do they not use/require the same SSL/TLS set up?  If they are working (which they were still working today) does that mean we have a different issue?

**Comment by adixon** [comment]
My best guess is that it was working with your TE0088 account because you had it configured with http instead of https. The issues you have don't appear to be connected with the account, but with the server-to-server connection (specifically - that's what the 9002 error indicates).

Re: your SSL/TLS test, here's what I'm getting

```
openssl s_client -quiet -tls1_2 -connect iatspayments.com:443
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign CloudSSL CA - SHA256 - G3
verify return:1
depth=0 C = US, ST = Delaware, L = Dover, O = Incapsula Inc, CN = incapsula.com
verify return:1

```
When I google your error (ie.. "verify error:num=20:unable to get local issuer certificate"), I see this helpful post: http://stackoverflow.com/questions/23343910/verify-errornum-20-when-connecting-to-gateway-sandbox-push-apple-com

And the answer suggests that your server is not configured properly, i.e. you are missing a root certficate on your server. I believe there are some distros that don't include one by default, but it should be relatively straightforward to get it via apt-get or yum. If you're running a windows server, then you'll have to do your own research.

I note that you write:

> We have checked that it is not a firewall issue. We have checked our SSL and TLS issues (running TLS 1.2).

You'll need to communicate with your server administrator, that this is not about being able to connect to your server, it's about your server connecting outwards. If you send your server admin to my link above there may be some useful data. And remind him/her that google is a useful tool when faced with error messages ...
