### ISSUE TITLE
Default Payment processor and multiple merchant accounts

### ISSUE THREAD

**Issue by justinrolfs** [iATSPayments/com.iatspayments.civicrm#199]
Trying to set up multiple donation pages with multiple merchant accounts.

Running CiviCRM version 4.7.19
iATS extension version 1.6.0
Drupal 7.54

We have set up two merchant accounts (US and Canadian) as well as two different payment types (Credit Card and ACH/EFT) for each merchant account.  We have noticed four unique items:

- Our donation pages work only if a Credit Card payment type is selected as the default payment processor.  We would like to set the default payment processor to ACH/EFT.

- The appropriate input fields **_do not_** show up on the Canadian EFT donation page if the default payment processor is the US Credit Card.  

- The appropriate input fields **_do_** show up on the Canadian EFT donation page if the default payment processor is the Canadian ACH/EFT.

- If the donation page does not have a default payment processor, the appropriate credit card or EFT bank information does not render correctly.

Any guidance on how to rectify the issue would be greatly appreciated.

**Comment by adixon** [comment]
You probably want to review the [notes with the 1.6 release](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/release-notes/1.6.0.md), you'll see there are some caveats when you want to have multiple payment processors on a single contribution page.

Your symptoms sound exactly like these caveats.

I believe there are some outstanding issues in CiviCRM core to address them.

In the meantime - basically, you'll likely want to create separate contribution pages for each of those four contribution modes and have your donor directed to them from a landing page. I should say that this is probably a good thing to do anyway, since the civicrm pages have not very nice urls.
