### ISSUE TITLE
Membership end date not updated for autorenew monthly

### ISSUE THREAD

**Issue by kngs** [iATSPayments/com.iatspayments.civicrm#217]
Ever since upgrading Civi in May from 4.6.18 to 4.7.19 (currently running 4.7.22), membership end dates are not getting updated for monthly autorenewing memberships. The completed contribution record is no longer being attached to the membership (thus no update to the end date). Earlier contribution records which worked have the membership type in the amount_level field in the civicrm_contribution table. New ones are NULL :/

These are all credit card transactions.
Using iATS 1.6.0 and Drupal.

Thanks! Karen

**Comment by KarinG** [comment]
Hey Karen - sorry for the delay - let me try reproduce this. It's tricky in that iATS extension itself just takes care of the monies; we use repeattransaction API in 4.7 -> and the fact that the recurring series is attached to a Membership - that should update it. I'll look into this - this week and will help file a JIRA for it / and possibly a test;

**Comment by guyiac** [comment]
Karin - any update?

**Comment by adixon** [comment]
I'm going to guess that there's an error happening in the renewal process after the money gets taken, and these various housekeeping bits (attaching the contribution to the membership and updating it) are not completing after that error. You should see more information about the error in the civicrm error log. I'd suspect it's unrelated to the contribution itslef, perhaps it's a membership custom field or an extension that's running a post contribution hook, etc.

**Comment by KarinG** [comment]
Trying to reproduce this now.

**Comment by KarinG** [comment]
Hi Karen - I just confirmed that CiviCRM 4.7 does properly renew Membership/recurring and the Contributions are properly attached to the Membership (below: daily recurring contribution which I triggered three times properly advanced end_date from Sep 07 -> Sep 08 -> Sep 09): I tested this on 4.7.22 RC - should be nearly identical to your 4.7.22

So hit the log files and see if you can find any clues/errors as to what may be going on with your instance.

![image](https://user-images.githubusercontent.com/5340555/30174498-8957dd20-93b8-11e7-86a1-fc772191cb1c.png)

**Comment by kngs** [comment]
Hi Karin and Alan,

We (Greenleaf Advancement) had our devs look at this, and determined it was necessary to change the hard coded 'contribution_status_id' => from 'Pending' to $status in com.iatspayments.civicrm/iats.php line 1349.  Do you concur with this change?

Thanks!, Karen

**Comment by KarinG** [comment]
I'm going to have to say - 'no' - because I could not reproduce the issue you were/are having; https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/iats.php#L1349 in current master does not contain 'contribution_status_id' - perhaps you're working off an older version of the iATS extension? Updating would be the first thing to do;

**Comment by adixon** [comment]
The hard coded Pending status is on line 1325 and is correct. Following the CiviCRM convention, we're creating all contributions as pending and then completing them (potentially, line 1358).

As I noted previously, the issue is likely that your system is hitting an error before it can do the post-contribution tasks such as membership renewal, etc.

If your patch means it's working for you, then there's some rule perhaps that's kicking in on the creation of pending contributions that shouldn't?
