### ISSUE TITLE
ACH Contributions showing Paid By = "Debit Card"

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#219]
When we make a one-time ACH contribution and then view the contribution details we notice Paid By = "Debit Card". We would expect these to be the "Virtual Check (EFT)" payment instrument that we created.

What we see in the code is that the payment instrument ID has been hard-coded to set to 2 in the case of an ACH/EFT transaction - which, in our Civi is Debit Card. Evidently, the code is not checking against either the selected payment processor, or any existing payment instruments, as one might expect.

In this thread (https://github.com/iATSPayments/com.iatspayments.civicrm/issues/184), it's noted that transactions are set to Debit Card in order for the verification process to complete, so this appears to have been a deliberate choice?  Should we change the Debit Card payment instrument to be ACH/EFT, or is  there another alternative that will still allow payments to be verified?

CiviCRM v4.6.14
iATS Payments extension v1.5.3
Drupal 7.43

**Comment by adixon** [comment]
Yes, the payment instrument thing was a bit misleading before v1.6. Once you update to 4.7 + 1.6, it'll actually modify the Debit card label to ACH/EFT and make sure all your ach contributions are using that. In theory, we might have made it configurable, but I took this route in the interest of simplicity.

In the meantime, you can just update the label of the payment instrument id = 2. There's a subtle connection between 'payment processor type id' and payment instrument id that makes this kind of hard-coding actually kind of sensible, though CiviCRM core support for non-cc payment processing still has some grey areas.

The 184 thread - yes, it's because one-time payments don't have a reliable way to identify their payment processor, so I chose to identify the outstanding ACH/EFT payments to complete using their payment type.
