### ISSUE TITLE
recurring option set as default

### ISSUE THREAD

**Issue by lcdservices** [iATSPayments/com.iatspayments.civicrm#237]
the recurring payment option is set as a default here: 
https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/iats.php#L888

what is the rationale for that? I don't think it should be assumed that organizations want the recurring option defaulted for contrib forms, and it's a bit tricky to undo that with a separate extension.

**Comment by KarinG** [comment]
This request came to us from orgs which have dedicated 'Donate Monthly' contributions with $amount / options and defaults specific to recurring series; then you want is_recurring checkbox - checked - or you risk donors thinking they started a recurring contribution when in fact they had missed a checkbox; 

For orgs who use combi [one time + monthly $amounts] pages - [and prefer recurring to be optional] - that box can easily be unchecked with some jquery:

```
      // Don't make recurring default 
      $("#is_recur").attr('checked', false);
```

**Comment by lcdservices** [comment]
I think this should be moved to a setting. I don't think you can make that assumption, as many orgs do make recurring optional.

Re: the jquery -- it's more complicated than that. You have to check if the form has already been submitted or whether it's an initial load, otherwise a checked value for that field will get lost if the submission fails validation and the form reloads.

**Comment by adixon** [comment]
To be clear - this only applies to ACH/EFT. The rationale is that ACH/EFT contributions are almost always expected to be recurring, and there's no way on the civi interface to configure recurring as the default, so this line improves the default experience. As you note, it's not that easy to change via js, which is why we do it here in code.

I find most of the time, even for credit card options, if the recurring option is enabled, it should normally be the default, and most of the time you don't wan the option of unclicking it. My extension here: 
https://github.com/adixon/ca.civicrm.contributionrecur
provides that.

If, with all that, you really think there is a common use case of providing ACH/EFT options where the default should not be recurring, then, yes it could be added as a configuration options.
