### ISSUE TITLE
Error 9002: Wrong encrypted track information

### ISSUE THREAD

**Issue by eruraindil** [iATSPayments/com.iatspayments.civicrm#261]
Hi there, one of my staff was at an event with our swipe card reader and encountered this error when processing payments through a contribution page. Of course I cannot replicate the issue today, using the same reader on the same contribution page works without problem now. There were no rejected transactions in in the iATS journal.

Can you let me know what this error means? Is this a miss-configuration of the card reader or our CRM? If we cannot trust the card reader to work, I am going to have a hard time getting my staff to use it.

Thanks

**Comment by adixon** [comment]
That error would have been passed back to CiviCRM from the iATS server, so I expect there was just an isolated data corruption error somewhere along the line (possibly the card being swiped, or the swipe device, or even the various cables/etc). When you swipe a card, it's just reading the card information and then encrypting it before sending it over to your civicrm install, which then uses that instead of the regular card information to process the transaction. CiviCRM got something from the device and sent it to iATS, which decided it wasn't a validly encrypted card. If you're using your setup and it's working on other cards, then I would assume you've got it all setup properly.
