### ISSUE TITLE
iATS Payments 1stPay Credit Card : 9002 : "Unable to retrieve merchant information"

### ISSUE THREAD

**Issue by rocxa** [iATSPayments/com.iatspayments.civicrm#312]
I have entered the live and test gateway information as found in the 1stpaygateway.net transaction centre into a new iATS Payments 1stPay Credit Card payment processor. Then added that processor to a contribution page and tried several test transactions.

I receive the error 9002 : "Unable to retrieve merchant information" once clicking 'confirm gift' every time with no further information on what this error means.  There appears to nowhere in the 1stpaygateway.net transaction centre that records a failed attempt either.

In the readme it says it can be a password issue.
`9002 Error - if you get this when trying to make a contribution, then you're getting that error back from the iATS server due to an account misconfiguration. One source is due to some special characters in your passwd.`

The password for the account should not be falling foul of this and it isn't used in the payment gateway settings anyway?

Any hints on how to debug this further? Have I misunderstood which gateway information I should have entered into the payment processor? It looks self explanatory as the fields on the edit payment processor form are named the same as they appear in the transaction centre. TransactionID, Processor ID and Merchant Key..

**Comment by rocxa** [comment]
Does this:
`Remember that iATS master accounts (ending in 01) can typically NOT be used to push monies into via web services. So when setting up your Account with iATS - ask them to create another (set of) Agent Codes for you: e.g. 80 or 90, etc.`
mean that the default 1stPay iATS accounts won't work with the civicrm extension or just shouldn't be used with the civicrm extension?

**Comment by rocxa** [comment]
Turning some of the debug info on in the code, it seems that the $Credentials array is missing the Transaction Center ID:

```
[info] $Credentials = Array
(
    [merchantKey] => 3***************
    [processorId] => 3*******
)
```

**Comment by KarinG** [comment]
@rocxa - the Documentation you are referencing re: subaccounts is re: iATS legacy payment processors. I'll make some updates to that. 

1stPay iATS will work with the Extension as is. All you need is TransactionID, Processor ID and Merchant Key.

I typically create two 1stPay iATS processors -> 

- one for TESTing with the TEST credentials in the LIVE section -> pay with fake VISA
- one for LIVE with the LIVE credentials in the LIVE section -> pay with real cards

**Comment by KarinG** [comment]
Have you contacted iATS Customer Service to confirm the account has been set up properly?

**Comment by KarinG** [comment]
Updated the README.md -> https://github.com/iATSPayments/com.iatspayments.civicrm/pull/313

**Comment by rocxa** [comment]
> Have you contacted iATS Customer Service to confirm the account has been set up properly?

Yes, I thought this was done, but I will get them to check.

**Comment by twjordan** [comment]
I am also seeing this error when trying to test my workflow. I have called iATS support and goemerchant and confirmed my configuration and account are correct.

I have tried the suggested approach of creating a "live" instance with the test data credentials & live ur (doesn't work, but it's a Cryptogram error, probably because it's a fake card) and I have tried using the test credentials and test url in the "live" processor spot, which returns a 9002: unknown error. 

I have tried using the secure-v.goemerchant.com url and the secure-v.1stpaygateway.net urls 

Is this software maintained by iATS or is it a completely volunteer effort?

**Comment by adixon** [comment]
The extension is maintained by Karin and I (we're both CiviCRM partners for some years), financially supported and with direction from iATS Payments.

Creating a test environment for the 1st pay version of the payment processor is a bit tricky, but my working one has the same 

Processor ID, Transaction Center ID and Merchant Key

and just swaps in the goemerchant domain. I did need me to call support for them to enable it first.

The confusion arises because there are two different kinds of 'test' environments and I can't recall what name they give each one.

**Comment by twjordan** [comment]
When I try my actual credentials (not the test ones) in the test processor
w/ a test page I get an error that it needs a cryptogram.  When I try the
method suggested by Karin and put the test url in the live section with my
credentials and try a “live” submission, I get 9002: Cryptogram Invalid.

Are you able to process a test transaction yourself? I am on the civicrm
chat as twjordan if you’d like to discuss this there.

I am happy to call goemerchant again, but I feel like I want to know
exactly what I am asking them because both they and iATS seem to want to
just point back at the plugin.

**Comment by adixon** [comment]
The specific thing you want to ask them is to enable a test account that uses your production credentials on that alternative/test domain.

Other combinations will fail for a variety of causes not worth pursuing.

The test domain + production credentials will allow the use of test credit cards only.

The production domain + production credentials will allow for the use of real credit cards only.

**Comment by twjordan** [comment]
Here is a rundown of how I was able to submit a test transaction. I will file another issue that the civiCRM plugin should be corrected so that the built in testing functionality can be used. 
https://gist.github.com/twjordan/68451998a68f072e079536f205486007

**Comment by rocxa** [comment]
> Here is a rundown of how I was able to submit a test transaction. I will file another issue that the civiCRM plugin should be corrected so that the built in testing functionality can be used.
> https://gist.github.com/twjordan/68451998a68f072e079536f205486007

I will test this out when I get iATS to enable the relevant accounts.  It would be good to then have a working set of steps for myself and others to follow.  Payments gateways should not be this difficult to setup. It will make everyone go over to Bitcoin.

**Comment by twjordan** [comment]
I don’t think you actually need to have them set up anything special (if
you already have access to the 1stPay transaction center). I sent you a
message on the matter most.

**Comment by adixon** [comment]
@twjordan  - wow, thank you. Yes, we need to check in with iATS/1stPay to get this working properly. I suspect the reason you're not able to use the civicrm preview/test option is because I've got some automation in there for the test processor that's breaking it. To be fair to me, I did have it working a few months ago after talking to them, but it seems like it's broken since then.

Thanks again for your pursuit.

**Comment by KarinG** [comment]
Thanks @twjordan 

My thoughts:

There have been issues with CiviCRM TEST pathways (regardless of Payment Processors) dating back years. I first ran into them using a PayPal pro for a client. Some were core issues; some were user issues e.g. "It's not working - I can't find the test contributions!" (users not understanding that Test contributions are not visible on the Contributions test) -> so we have always (even with iATS Legacy payment processors) recommended that users (line 47 in README.md) test with live CiviCRM workflows:

`...use the test account credentials in your live processor fields.`

It's the only way you can know for sure that your entire CiviCRM workflow is working (e.g. Membership successfully renewed, GST recorded properly in financial accounts, Participant is successfully registered for Event).

The process for Test Payment Processors (for 1stPay) used to be: Call iATS -> set up a 1stPay Test Account - Looking at one of Alan's clients - we can see Test Contributions dating back to April (when the 1st Pay processor was set up for that client). This is however no longer working at this time [Test Contributions are now failing] - so something is definitely different from what it used to be.

Following your steps on my own 1stPay account just now -> setting up a 1stPay sandbox -> getting 9002: unknown error [as if something still has to be activated in addition to what I just configured myself in the Transaction Centre].

I'll touch base with one of the iATS managers to check and see what if there have been any changes in process re: Test Account setups. Obviously we want to ensure people can transact using fake VISAs for testing and that we have a document process for that. 

And we'll make edits from there to docs and/or to code!

PS -  live workflows in CiviCRM is as close to the real thing as possible [which is what you want]. All our clients are using live workflows for testing. Yes it's a little bit more clean up - but it's as close to the real thing as you can get.

**Comment by KarinG** [comment]
**Add on ->** your TEST credit card credentials are different than the TEST credit card credentials I've used to date. I AM able to get your instructions to work with -> VISA 4539394673694021 (but not with the TEST credentials I've used successfully in the past for our test matrix). 

Ok setting up a call w/ iATS. Stay tuned!

**Comment by twjordan** [comment]
The test credit card number from that appendix was the final piece of the puzzle. The whole REST API docs would be good to have referenced in the documentation for the plugin too.

I recognize the need to occasionally run a test on the live forms (I ran a real donation as a test with my credit card) but for things like testing receipts, mailings, etc, I really want to be able to swap over to the test form and submit a few transactions to make sure the civiCRM side of things is working.

**Comment by rocxa** [comment]
I have progressed slightly and now also get the "9002: Cryptogram Failed" error.

I am using the sandbox account Transaction Center ID, Processor ID and Merchant Key.  Do I also need to use the MID/ACH Username or the TIDs under the 'Sandbox MIDS/TIDS' section? they are not mentioned anywhere or requested by the payment processor setup screen in CiviCRM.

**Comment by rocxa** [comment]
So, 

- Using the test card details from here:
https://support.goemerchant.com/gateway/Docs/Appendix/TestData.html

- Using a LIVE payment gateway with the test account details and test goemerchant url

- Checking with iATS the account is setup correctly..

I still get CyrptoGram error and occasionally the unable to retrieve merchant data.

**Comment by rocxa** [comment]
So the solution (to run a successful test payment):
- Use the test card detail that always approves from here https://support.goemerchant.com/gateway/Docs/Appendix/TestData.html
- Use the live url, not goemerchant or validation area
- Use the sandbox processorID from iATS, but in a LIVE civicrm payment processor

Now to test ACH.. as the above its just for the credit card gateway.
