### ISSUE TITLE
Failed transaction resulting in contributions recurring every day

### ISSUE THREAD

**Issue by flatbus** [iATSPayments/com.iatspayments.civicrm#325]
In the Contributions tab in Civi, I can see that a user has the status "Pending (Incomplete Transaction)" on July 8th, 2020. Since then there have been no recorded payments in Civi. However, in iats, I see the same person has been charged every day for what ought to be a monthly charge. Our civi instance is the only user of iats so there is not an additional script or software that could be charging the user this amount. It looks like indefinite (successful) retries every day.

Civi version: 5.21.1
iATS payments: 1.7.1

Cron is looking good.

**Comment by adixon** [comment]
The general process of a civicrm payment is:
1. Generate a pending contribution.
2. Try to take the money.
3. complete the contribution on success, mark as failed on failure, update the next scheduled contribution as appropriate.

What you're describing tells me that step 3. is not happening, probably due to a server failure (your server). Check the civicrm and/or server logs for details and also edit this recurring contribution until you've fixed it.

Note that 1.7.2 has addressed this issue (i.e. the server failure handling) by pushing forward the next scheduled contribution before trying to take the money.
