### ISSUE TITLE
Mandatory key(s) missing from params array: entity_id

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#329]
Starting on 2020-08-31, we are seeing this error in the Scheduled Job Logs, and it has happened every time since then.

iATS Payments Verification (Hourly), failing with this error:

```
Full message: 
Finished execution of iATS Payments Verification with result: Failure, Error message: 
Found 106 contributions to verify.
Completed with 84 errors.
Processed 84 approvals, 0 pending and 0 rejection records from the previous 30 days.
Failed to complete transaction: Mandatory key(s) missing from params array: entity_id
Failed to complete transaction: Mandatory key(s) missing from params array: entity_id
```
...

We also see this error in the iATS Payments Recurring Contributions schedule job log:

```
Full message: 
Finished execution of iATS Payments Recurring Contributions with result: Failure, Error message: DB Error: constraint violation
```

Note, we installed CiviMobile on 8/28/2020. But, the iATS Payments Verification error continues to occur even if we disable the CiviMobileAPI extension. So, not sure if it is the culprit.

Can you help us figure out how to fix this?

CiviCRM 5.24.5, iATS Payments 1.7.2, Drupal 7.69

Thank you!

**Comment by cmmadmin** [comment]
And we see several errors like this in the Civi log when the iATS Payments Verification job runs:

```
Sep 15 10:06:17  [info] $Failed to complete transaction with = Array
(
    [version] => 3
    [id] => 370006
    [trxn_id] => ACB783FB:1523182527
    [receive_date] => 2020-08-30 02:30:42
    [is_email_receipt] => 0
)
```

**Comment by adixon** [comment]
Okay, so this is an error from the job that updates contributions that are listed in CiviCRM as pending/incomplete by testing those contributions against transaction data from iATS. It's generating an error due to a missing 'entity_id' while executing the civicrm api action of 'completetransaction'.

I'm happy (selfishly) to observe that this doesn't seem to be an iATS extension code issue - that error in your civi log is the extension helpfully telling you the parameters that it passed in to the completetransaction api call, and it's showing you the contribution id (in your example = 370006).

I'd recommend you look up that contribution and see what might be missing from it, I suspect it was created w/ incomplete information, perhaps as a result of that earlier civimobile issue (e.g. perhaps that contribution record is missing a contact id reference?).

Your second error is being generated by your recurring contributions job - this is a different beast and it's harder to tell how to fix that. I suspect you should see some logging showing the details of the 'db error'. The recurring contributions job itself doesn't make any direct sql calls, so I'd assume it's also a result of an api call that's triggering some kind of db/sql error due to some bad internal data - i.e. if you figure out your first error, it might fix the second one.

Also - I'm hoping that second error is not interfering with the generation of new contributions in your recurring series? i.e. it's only an error during the cleanup/reporting part of the job?

**Comment by cmmadmin** [comment]
Thanks Alan. It turns out CiviMobile was adding a record to a table in the database for every notification which pushed our server to the limit. We upgraded our server, uninstalled CiviMobile and fixed the status of the recurring contributions. Everything is working fine now. Appreciate your help.
