### ISSUE TITLE
Exp date on view recurring contribution series -> 1969-12

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#342]
![image](https://user-images.githubusercontent.com/5340555/100366095-a34d2b00-2fbd-11eb-873d-1e0628ef9f9e.png)

Expiry in this screen was only the card used to initiate the recurring series transaction -> hit View again (at the bottom there) to see the current card on file details.

But 1969-12 is definitively a bug that can be fixed - not at all critical though.

**Comment by adixon** [comment]
Noted. I'm not at all sure that field should still exist, core does some tracking of expiry dates and that card on file link will pull up the real expiry date.

FWIW - 1969-12 being generated from an empty unix timestamp.

**Comment by KarinG** [comment]
I know and I agree -> best we don't store that field at all - after a few years it has no added value to know what the expiry date was the day that donor started their recurring contribution series. We can keep it on the list of things to do for a next round of updates.

**Comment by adixon** [comment]
Fixed with https://github.com/iATSPayments/com.iatspayments.civicrm/commit/6aef38a6583b09827cdc6cf1727deb88b8c6c1b3

Fixed by showing N/A if the expiry date string is empty.

In fact, we're not storing it, the civicrm payment token table is, and it does get updated when civicrm is used to update card credentials, so it's not a terrible thing. All I'm doing with this piece of code is exposing that field to the view of the recurring schedule, for credit cards, which at some point might be something core could do.
