### ISSUE TITLE
Best process for changing credit card number on recurring contributions?

### ISSUE THREAD

**Issue by JoeMurray** [iATSPayments/com.iatspayments.civicrm#360]
When an expiry date on a card or the card number change, there is a form to edit the credit card. It does not have a field for entering a CVC field (https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/CRM/Iats/Form/IATSCustomerLink.php#L94).

We have a report that when a new card number is entered via this CiviCRM form the organization gets failures on subsequent attempts to use that card in CiviCRM. If they change the card in the iATS interface directly then the payments are going through.

Suggestions on what is happening here and how to address would be appreciated.

**Comment by adixon** [comment]
Thanks for the report, I haven't heard of anything similar (yet).

The interface for the customer link form is detailed here:
https://www.iatspayments.com/NetGate/CustomerLink.asmx?op=UpdateCreditCardCustomerCodeV1

From a quick review, it's not offering a cvc field.

You might talk to iATS directly about this, it'd be up to them to add that field and/or confirm the behaviour you're observing.

From a security/PCI perspective, this might actually be correct - i.e. as an administrator, you wouldn't normally be handling the CVC field, that would be the responsibility of the customer themselves. Updating card numbers and expiry numbers through that interface, on behalf of the card holder would make sense, but I think you might be crossing a pci line if your administrators are using it to input completely new cards or updating cvc numbers.

If a customer has a completely new card or an updated cvc number, you can of course just use the civicrm-native form instead of the customerlink form.

**Comment by JoeMurray** [comment]
Thx @adixon . Cheers.
