### ISSUE TITLE
Monthly recurring transaction is processed daily

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#53]
There is an ACH recurring contribution that is scheduled to process monthly. (on the 8th of each month)  It is not connected to membership. 

Starting Dec 16, it is being processed daily (ie transactions are listed in the iATS portal) but are NOT listed in CiviCRM. The "Next Contribution" date for the recurring schedule  is listed as Dec. 8 in CiviCRM.

Ideas on how to fix?

**Comment by KarinG** [comment]
Instead of make code edits to the iATS extension - I strongly encourage you to make your Payment Processor Helper extension an ad-hoc post-transaction extension. Let payment processor extensions do what they do - do not make any code edits - then run a post-recurring-bookkeeping extension that distributes the total amount over the applicable line items ad-hoc.

**Comment by sgladstone** [comment]
Karin  - I updated the extension to version 1.3.1 and the extension is working as expected.    FYI: I am trying to get an update on the broken CiviCRM API issue. You may want to comment too. See forum post at: http://forum.civicrm.org/index.php/topic,35398.0.html
