### ISSUE TITLE
Compatibility with another extension

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#57]
I have developed a CiviCRM native extension ( https://github.com/sgladstone/com.pogstone.pmt2recur)  that works well with non-iATS automated recurring contributions.  The purpose of the other extension is to allow the bookkeeper to record a mailed check to cover a missed/failed automated contribution. Since there is no payment-processor specific code in the "pmt2recur" extension, I was hoping it would work with automated recurring contributions that are created via the iATS extension.   However, in my testing the "payment instrument" gets changed from "check" (or whatever the user entered) to "Debit Card" and the status gets changed to "Pending".   (This is not happening with non-iATS recurring contributions)  

What is your suggestion for allowing the bookkeeper to deal with mailed checks in the situation where an automated transaction has failed?  Could this iATS extension be changed to NOT alter a human-entered contribution record?

**Comment by adixon** [comment]
I presume it's the iats_civicrm_pre function that's interfering with the payment instrument and status. It'll only do that if it sees that the payment is attached to it's recurring payment processor, and I assume that's what your code must be doing, inadvertendly. I'm not sure how we could do this otherwise until the payment processor code is cleaned up in the next release. Is there another way that the replacement contribution could be identified as a replacement without linking it to the recurring series [which is how it is getting identified as processed by the iats payment processor in the pre function].

Alternatively, is there something in that record you're writing that would help us identify these manual submissions?

**Comment by sgladstone** [comment]
I cannot think of a way to associate a manually created contribution with the schedule its for, other than what my extension is already doing. 

A simple way to differentiate these manually entered records would be to check the "source" field. The contribution source that the iATS scheduled job fills in makes it easy to spot contributions from the scheduled job vs human-entered contributions.  

A more robust way is to do a join to the tables "civicrm_activity" and "civicrm_activity_contact"  for the activity for that contribution. The "created by" contact on the activity record makes it easy to differentiate user-created contributions vs scheduled job created.

**Comment by adixon** [comment]
Well, it's not quite like that. Contributions with an associated recur_id are created first of all as the initial contribution of a series, and then as that recurring contribution job. I don't think I even need to worry about the ones created by the job - that _pre code is really just dealing with the core code that makes bad assumptions [in this case, it's dealing with the payment instrument problem for first and one-time ACH/EFT, and the status for one-time ACH/EFT].

Here's a more straightforward logic - how about we don't intervene if there's no transaction id? Anything created that corresponds to an actual transaction with the payment processor will have that transaction id, so you can just create yours without a transaction id and we can skip the forcing in the logic.

That'll also make it easy for you to separate out those contributions in a fairly obvious way.

**Comment by sgladstone** [comment]
Sometimes there is a transaction id - For example the bookkeeper clicks the "Create New.... Contribution (Credit Card)" and submits a one-time contribution. The bookkeeper then manually links this contribution with the recurring schedule.    I think the source is more reliable - the source your extension puts in is not something a bookkeeper would ever use.

**Comment by adixon** [comment]
I think your process is getting a bit dangerous. The presence of the recurring contribution id in the contribution record isn't designed for manually being set (which is why there is no web interface to change it), and reasonably carries a lot of assumptions with it.

The real nub of the issue here is that contributions aren't actually directly linked to a transaction processor - they're only linked indirectly via few hints, which is why your contributions getting assumed to be generated as the iATS ACH/EFT and that's why they're getting mangled.

For your needs, I wonder if there's a different way that you can keep track of this one-time contribution to associate it with the other ones in the series, presumably for bookkeeping purposes?

**Comment by sgladstone** [comment]
I have researched this for a long time, and the only way I could find to associate the one-time contribution with the series was to add the recurring ID into the contribution record.

Until there is a better mechanism in civicrm core, can you update your extension to not edit/change contribution records that do not have the standard iATS source. It seems a bit dangerous for your extension to edit contribution records that you do not confirm that they were generated by the iATS scheduled job.

**Comment by adixon** [comment]
No, remember that the intervention is required for the first of a recurring series, and for those contributions, the source is set manually or by the contribution page, not by the iats payment processor code. These are not contributions generated by the scheduled job.

We're finally getting some code in to fix the status forcing in core [thanks Eileen!], so we I'll review how much forcing is required when 4.6 is out.
