### ISSUE TITLE
URGENT: iATS Recurring Contribution Receipts "from" Address Populating from User 1 instead of Organization Address & Contact Infor

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#98]
Hi All,

As the title states, it seems that for recurring subscriptions, the iATS extension is taking the "from address from the "User 1" account as opposed to Administer > Communications > Organization Address & Contact Info. This was reported to us by a couple of members of one of our clients and we were breaking our heads on why it was happening b/c nowhere in the system was the User 1 account information listed in the "from" addresses, but it wasn't until 2 other members of a different client reported the same issue that we realized the commonality must be in the iATS extension, and the issue is occurring with both CC and ACH recurring subscriptions. Both clients who have reported the issue reside on the same server are on the following related software versions:

CMS Drupal v6.16
Civi v4.4.7
iATS v1.4.1

Most of these clients have additional payment processors other than iATS, but no issues have been reported with those recurring receipts as of yet.

As a stop-gap measure, I have updated the "User 1" account for the clients we have on iATS to read the same as what appears in the organization name and email address fields. If this issue is a result of a configuration that was missed when updating to iATS v.1.4.1, please send a link to the relevant documentation (again, googling up and down, the only documentation I have found regarding this latest release is minimal at the following link: https://github.com/iATSPayments/com.iatspayments.civicrm, so if there is a different link, please send it - no encouragement to read necessary - I am self-motivated)

Thanks!

**Comment by KarinG** [comment]
The iATS extension does not compose Emails. CiviCRM core does. Using CiviCRM 4.6 (latest) - email receipt for recurring contributions - all is working as expected.

I just verified this:

Initiating Recurring Contributions - receipts:
- If the recurring contribution is made via a contribution pages - the email From is what's configured in the contributions page (Thank you section): "Donations Department" <noreply@semper-it.com>
- If the recurring contribution is via the backend -> the default Receipt From address is the Email address configured in CiviCRM -> Communications -> etc. "iATS Payment Demo" <demo@iatspayments.com>

Scheduled Job triggered Recurring Contribution - receipts:
- the Receipt From address is the Email address configured in CiviCRM -> Communications -> etc. "iATS Payment Demo" <demo@iatspayments.com>

Many fixes in CiviCRM core 4.6 related to payment processing have been back ported to CiviCRM 4.4.x -> so I encourage you to upgrade from 4.4.7 to latest 4.4.x which is 4.4.19 at the moment. If this fixes this particular bug I can't tell off hand - but there is no doubt there have been many bug fixes related to payment processing since 4.4.7 - not to mention security updates. 

The reason you may see this for the iATS extension on 4.4.7 but not for other payment processors is that there have been lots of improvements to CiviCRM core over the past year for non-IPN payment processors - and iATS belongs to that class of payment processors.

**Comment by adixon** [comment]
Thanks for your report. This email function (new) is based on the api, so it appears that the default from address and name built into your version of the api is the uid = 1. The api call (completetransaction) does have the ability to specify the from name and address, so in theory, we could do that, but as per Karin's note above, upgrading to the latest version of your major version is always recommended anyway and is a better solution.

**Comment by tamarmeir** [comment]
Thanks to you both for the clarifications and rapid responses - it will be a couple of months yet before we are able to upgrade our clients, is it possible to obtain a patch for this, or specific direction as to where the code needs to be changed in the api? Again, please don't shoot me if my question sounds stupid, I am not a programmer.

Thanks again for your time!

**Comment by KarinG** [comment]
You're well >1y behind in updates though this - the From email address is not the biggest issue here.

**Comment by tamarmeir** [comment]
Karin, 100% correct, however, my hands are tied so any help you can offer would be greatly appreciated. 

But I just thought of something - this issue only surfaced after we updated the iATS extension to v 1.4.1 - previously it was working according to what Karin tested (and that does work for initial installments, apparently, the issue occurs only with subsequent installments). If the api is set to UID 1, then wouldn't this have occurred with the previous version of iATS (v. 1.3.1) before we updated?

**Comment by KarinG** [comment]
The completetransaction API is new. Previously no emails went out for scheduled job triggered recurring contributions.

**Comment by tamarmeir** [comment]
Hi guys,

I am just writing back to say thanks for your efforts - I thought it might be a trivial fix but according to one of the developers we work with, it turns out that it is not, so we just need to update our clients and I agree that it shouldn't be anyone else's responsibility to provide us patches for an issue that is caused because we are so out of date. I implemented a stop gap measure that should tide us over - I entered the organization name and from email address in UID 1, so if that's what the api wants to use, at least it will make sense to our clients' members. Just thought I would post this in case anyone else out there is as behind as we are in civi updates, and I wanted to make sure that you guys knew that I really appreciate your time.

Kind regards,
Tamar

**Comment by jmcclelland** [comment]
Hi all - I think this issue needs to be re-opened. It seems to be affecting CiviCRM 4.7 and the most recent releaseof iATS. However, I suspect the bug might be a CiviCRM bug (or at least the fix may need to happen in CiviCRM).

In any event - I will document here.

 * The _iats_process_contribution_payment() calls the completetransaction API, and it properly tells it whether or not to send a receipt. I think that's it for the iATS code's responsibility.
 * civicrm_api3_contribution_completetransaction calls _ipn_process_transaction()
 * _ipn_process_transaction calls  CRM_Contribute_BAO_Contribution::completeOrder
 * CRM_Contribute_BAO_Contribution::completeOrder calls 'sendconfirmation' API, but it only sends the contribution_id and the payment_processor_id - no additional parameters.
 * civicrm_api3_contribution_sendconfirmation allows you to pass in the from email and from name, it then calls CRM_Contribute_BAO_Contribution::sendMail, passing on the from name and email if it was given that info. 
 * CRM_Contribute_BAO_Contribution::sendMail in turn will set the from name and email to the current logged in user if they are not set.  

It seems like the problem is with CRM_Contribute_BAO_Contribution::sendMail.

**Comment by jmcclelland** [comment]
Since this issue is closed, I opened a new one at #170.
