### ISSUE TITLE
Payment Processor ID Missing

### ISSUE THREAD

**Issue by stevekessler** [iATSPayments/com.iatspayments.civicrm#99]
We are running CiviCRM 4.5.8 and the iATS Extension version 1.4.0. When the contribution is saved in the database, the payment processor ID is missing. This works fine if you only have one payment processor because it goes to the default financial account.  However, we are using two payment processors on one of our sites and we cannot accurately report on our transactions by financial account because the ID is not saved.  

Please let me know if you need anything else from me to come up with a resolution for this issue. 

Thanks,
Steve

**Comment by adixon** [comment]
Yes, that's a design challenge with CiviCRM. You can work around it in a few ways (usually involving civicrm's FInancial Types), but it kind of depends - why do you have two payment processors?

The payment processor id is actually in a table, just not in the contribution table (which is not unreasonable, since you may have multple payments for a single contribution, in theory). So you might find a report that will generate the data you want, or you might have to write one yourself.

I'd suggest posting your question over on http://civicrm.stackexchange.com/
